// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;
import 'dart:io' show Platform;

/// `FirebaseOptions` for Android
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    if (Platform.isAndroid) {
      return android;
    }
    if (Platform.isIOS) {
      return ios;
    }
    if (Platform.isMacOS) {
      return macos;
    }
    if (Platform.isWindows) {
      return windows;
    }
    if (Platform.isLinux) {
      return linux;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyzVIIKA40ruDrS9rIuy4e6CIVdBa2PEU',
    appId: '1:36322493034:android:b8bb4f64139b9160448013',
    messagingSenderId: '36322493034',
    projectId: 'gamezone-45d28',
    storageBucket: 'gamezone-45d28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyzVIIKA40ruDrS9rIuy4e6CIVdBa2PEU',
    appId: '1:36322493034:ios:7ou4jui2s4vdqbol9f2e9mshlm6vf4ar',
    messagingSenderId: '36322493034',
    projectId: 'gamezone-45d28',
    storageBucket: 'gamezone-45d28.firebasestorage.app',
    iosBundleId: 'com.example.gamezone',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyzVIIKA40ruDrS9rIuy4e6CIVdBa2PEU',
    appId: '1:36322493034:web:12345678901234567890',
    messagingSenderId: '36322493034',
    projectId: 'gamezone-45d28',
    storageBucket: 'gamezone-45d28.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyzVIIKA40ruDrS9rIuy4e6CIVdBa2PEU',
    appId: '1:36322493034:macos:7ou4jui2s4vdqbol9f2e9mshlm6vf4ar',
    messagingSenderId: '36322493034',
    projectId: 'gamezone-45d28',
    storageBucket: 'gamezone-45d28.firebasestorage.app',
    iosBundleId: 'com.example.gamezone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyzVIIKA40ruDrS9rIuy4e6CIVdBa2PEU',
    appId: '1:36322493034:windows:12345678901234567890',
    messagingSenderId: '36322493034',
    projectId: 'gamezone-45d28',
    storageBucket: 'gamezone-45d28.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAyzVIIKA40ruDrS9rIuy4e6CIVdBa2PEU',
    appId: '1:36322493034:linux:12345678901234567890',
    messagingSenderId: '36322493034',
    projectId: 'gamezone-45d28',
    storageBucket: 'gamezone-45d28.firebasestorage.app',
  );
}
