// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz1cjiN0zd_Z-i2XCrBQck2Xrw73eF0No',
    appId: '1:382706650946:web:ee56d096b36fe9e4d902db',
    messagingSenderId: '382706650946',
    projectId: 'belajarflutter-mobile',
    authDomain: 'belajarflutter-mobile.firebaseapp.com',
    storageBucket: 'belajarflutter-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfn4Erq8Rx1vvuyZGOOky4sE9juaMUDVc',
    appId: '1:382706650946:android:24a40bee9c32e90bd902db',
    messagingSenderId: '382706650946',
    projectId: 'belajarflutter-mobile',
    storageBucket: 'belajarflutter-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiifXi5tLhxfQYZEgjURb0Y8emFOVZu7E',
    appId: '1:382706650946:ios:5a7617ed7d431ee9d902db',
    messagingSenderId: '382706650946',
    projectId: 'belajarflutter-mobile',
    storageBucket: 'belajarflutter-mobile.firebasestorage.app',
    iosBundleId: 'com.example.belajarflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiifXi5tLhxfQYZEgjURb0Y8emFOVZu7E',
    appId: '1:382706650946:ios:5a7617ed7d431ee9d902db',
    messagingSenderId: '382706650946',
    projectId: 'belajarflutter-mobile',
    storageBucket: 'belajarflutter-mobile.firebasestorage.app',
    iosBundleId: 'com.example.belajarflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz1cjiN0zd_Z-i2XCrBQck2Xrw73eF0No',
    appId: '1:382706650946:web:0a397e2c28dd95bed902db',
    messagingSenderId: '382706650946',
    projectId: 'belajarflutter-mobile',
    authDomain: 'belajarflutter-mobile.firebaseapp.com',
    storageBucket: 'belajarflutter-mobile.firebasestorage.app',
  );
}
